channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip=22.1.2
  - pip:
      - robocorp-storage==1.0.0
      - robocorp-tasks==2.2.0
      - robocorp-vault==1.3.0
      - robocorp-workitems==1.4.0
      - beautifulsoup4==4.12.2
