[tool.robo]
name = "Empty project"
description = "An empty automation project"
python = "3.9.13"

[tool.robo.dependencies]
robocorp-tasks="2.2.0"
robocorp-workitems="1.4.0"
robocorp-vault="1.3.0"
robocorp-storage="1.0.0"
